[package]
name = "luminos-contracts"
version = "0.1.0"
edition = "2024"
authors = ["joseph@raubstudios.com"]
description = "luminos Contracts"
repository = "https://github.com/RaubJo/luminos-contracts"
license = "MIT"

[lints.rust]
dead_code = "allow"
unused = "allow"
